os:
  - linx
  - osx

language: c
sudo: false

env:
  matrix:
    - CONDA_PY=2.7
    - CONDA_PY=3.4
    - CONDA_PY=3.5
    - CONDA_PY=3.6
  global:
    - PYSAM_LINKING_TEST=1

addons:
  apt:
    packages:
    - gcc
    - g++

script:
  - ./run_tests_travis.sh

notifications:
  email:
    - andreas.heger@gmail.com
