os:
  - linx
  - osx

language: c

env:
  matrix:
    - CONDA_PY=2.7
    - CONDA_PY=3.6
    - CONDA_PY=3.7
  global:
    - PYSAM_LINKING_TEST=1

addons:
  apt:
    packages:
    - gcc
    - g++

script:
  - ./devtools/run_tests_travis.sh

notifications:
  email:
    - andreas.heger@gmail.com
