os:
  - linux
  - osx

language: c

env:
  matrix:
    - CONDA_PY=2.7
    - CONDA_PY=3.6
    - CONDA_PY=3.7
  global:
    - PYSAM_LINKING_TEST=1
    - TWINE_USERNAME=grepall
    - secure: bTbky3Un19NAl62lix8bMLmBv9IGNhFkRXlZH+B253nYub7jwQwPQKum3ct9ea+XHJT5//uM0B8WAF6eyugpNkPQ7+S7SEH5BJuCt30nv6qvGhSO2AffZKeHEDnfW2kqGrivn87TqeomlSBlO742CD/V0wOIUwkTT9tutd+E7FU=

_deploy_common: &deploy_common
  if: branch = master AND type = push AND fork = false
  install:
    - python3 -m pip install cibuildwheel twine

matrix:
  include:
    - stage: deploy
      os: linux
      language: python
      python: '3.5'
      services:
        - docker
      env:
        - CIBW_BEFORE_BUILD="yum install -y zlib-devel bzip2-devel xz-devel && pip install -r requirements.txt"
        - CIBW_ENVIRONMENT='HTSLIB_CONFIGURE_OPTIONS="--disable-libcurl"'
	- CIBW_TEST_COMMAND='python -c "import pysam"'
      addons:
        apt:
          packages:
            - gcc
            - g++
            - libcurl4-openssl-dev  # for libcurl support in sdist
            - libssl-dev  # for s3 support in sdist
      <<: *deploy_common
      script:
        - set -e
        - cibuildwheel --output-dir dist
        - python3 -m pip install Cython
        - python3 setup.py build_ext --inplace
        - python3 setup.py sdist
        - twine check dist/*
#        - twine upload --skip-existing dist/*
    - stage: deploy
      os: osx
      language: generic
      env:
        - CIBW_BEFORE_BUILD="pip install -r requirements.txt"
        - CIBW_ENVIRONMENT='HTSLIB_CONFIGURE_OPTIONS="--disable-libcurl"'
	- CIBW_TEST_COMMAND='python -c "import pysam"'
      addons: {}
      <<: *deploy_common
      script:
        - set -e
        - cibuildwheel --output-dir dist
        - twine check dist/*
#       - twine upload --skip-existing dist/*

addons:
  apt:
    packages:
    - gcc
    - g++

script:
  - ./devtools/run_tests_travis.sh

notifications:
  email:
    - andreas.heger@gmail.com
